### ISSUE TITLE
More promise related rules

### ISSUE THREAD

**Issue by xjamundx** [jden/eslint-plugin-promiseparams#2]
Hey @jden would you have any interest in adding additional promise related rules such as the one proposed here? https://github.com/eslint/eslint/issues/1092

I'd be happy to write the code for it.

**Comment by junosuarez** [comment]
I don't have much experience writing eslint plugins, so I'm not sure if it makes more sense to have them all granular as separate packages or clump them together. Either way, I support it.

**Comment by xjamundx** [comment]
Yeah it's definitely common to pile more than one rule into a single plugin, but the name is pretty darn specific. I'll work together a PR and we can decide if it's worth combining or not. thanks!

**Comment by xjamundx** [comment]
Hey so I sort of...made a stab at re-imagining this as a more generic promise rule. I don't know if thats what you want at all and I'm happy just to fork your thing and call it a fork, but if you want to take these changes I'd be happy with that as well :)

**Comment by junosuarez** [comment]
The name is pretty specific, and I don't want to confuse issues with the npm package name (I'm currently using it in my build process on a project at work). I think the better direction is to create the new more generic promise rules package in a new repo. If you'd like, I'm happy to place a deprecation / forwarding warning in the readme of this repo and republish that as a patch version on npm.

**Comment by junosuarez** [comment]
Let's move discussion to PR #3
